language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.5.7 DJANGO_SETTINGS_MODULE="django_common.test_settings"
  - DJANGO=1.6.4 DJANGO_SETTINGS_MODULE="django_common.test_settings"
install:
  - pip install -q Django==$DJANGO --use-mirrors
script:
  - python setup.py test
