language: python
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO=1.7.11
  - DJANGO=1.8.9
  - DJANGO=1.9.2
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coveralls
  - pip install -r rest_auth/tests/requirements.pip
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO=1.7.11
script:
  - coverage run --source=rest_auth setup.py test
after_success:
  - coveralls
before_script:
  - flake8 . --config=flake8
