version: 2.1
orbs:
  docker: circleci/docker@0.6.0

jobs:
  test:
    docker:
      - image: circleci/python:3.8.0
    executor: docker/docker
    steps:
      - checkout
      - run:
          command: pip install --user tox coverage coveralls
          name: "Install Tox & Coverage"
      - run:
          command: tox
          name: "Run Tox on All Supported Django and Python Versions"
      - run:
          command: |
            mkdir -p test-results/
            tox -e coverage
          name: "Generate Coverage Report"
      - run:
          command: COVERALLS_REPO_TOKEN=Q58WdUuZOi89XHyDeDsGE2lxUGQ2IfqP3 coveralls
          name: "Send results to Coveralls"
      - store_test_results:
          path: test-results/
  build:
    docker:
      - image: circleci/python:3.8.0
    executor: docker/docker
    steps:
      - checkout
      - run:
          command: python3 setup.py sdist
          name: Build
      - store_artifacts:
          path: dist/

workflows:
  main:
    jobs:
      - test
      - build:
          requires:
            - test
